name: Lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: '12.x'
      - name: Install project
        run: npm ci
      - name: Lint
        run: npm run lint
