name: Lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1
      - name: Setup node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '12.x'
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
      - name: Check formatting
        run: npm run format:check
