name: Release test
on:
  push:
    branches:
      - main
jobs:
  get-version:
    if: |
      github.event.commits[0].message ==
          'chore(release): trigger release process [ci release]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup node
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version: '12.x'
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Build (artefacts)
        run: |
          npm run build
          npm link
      - name: Get release version
        run: next-standard-version
