name: Release test
on:
  push:
    branches:
      - main
jobs:
  get-version:
    if: |
      github.event.commits[0].message ==
          'chore(release): trigger release process [ci release]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '12.x'
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Build (artefacts)
        run: |
          npm run build
          npm link
      - name: Get release version
        run: next-standard-version
