name: Release
on:
  push:
    branches:
      - master
jobs:
  get-version:
    runs-on: ubuntu-latest
    if: |
      github.event.commits[0].message ==
          'chore(release): trigger release process [ci release]'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: '12.x'
      - name: Install project
        run: npm ci
      - name: Build (artefacts)
        run: |
          npm run build
          npm link
      - name: Get release version
        run: next-standard-version > VERSION
      - name: Save VERSION for following jobs
        uses: actions/upload-artifact@v1.0.0
        with:
          name: version
          path: VERSION
  release:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 0
      - name: Get VERSION
        uses: actions/download-artifact@v1.0.0
        with:
          name: version
      - name: Save version for later steps
        id: version
        run: echo "::set-output name=version::$(cat version/VERSION)"
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Setup node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: '12.x'
      - name: Install project
        run: npm ci
      - name: Build (artefacts)
        run: |
          npm run build
          npm link
      - name: Release
        run: npx --no-install standard-version
      - name: Get changelog section
        id: changelog
        run: |
          changelog="$(git show --unified=0 CHANGELOG.md \
              | tail +12 \
              | sed -e 's/^\+//' \
              | sed -z 's/\n/%0A/g;s/\r/%0D/g')"
          echo "::set-output name=changelog::${changelog}"
      - name: Publish npm package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
      - name: Publish release artefacts
        run: git push --follow-tags
      - name: Publish GitHub release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: v${{ steps.version.outputs.version }}
          body: |
            *See the the [changelog](
              https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md
            ) for changes in all releases.*

            ${{ steps.changelog.outputs.changelog }}
  prevent-failed-status:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent failed status when skipped
        run: |
          echo "Run this job to prevent the workflow status from showing as" \
              "failed when all other jobs are skipped."
